Repository bobbylight/RSyntaxTextArea, pull requests merged in 2024-11, with the labels that each got.

#573 Remove xvfb-action since it's bundled in Ubuntu CI images
  .github/workflows/gradle.yml
Labels: ci/cd

#577 Update RSyntaxTextArea.java
  RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/RSyntaxTextArea.java
Labels: bug

#582 Fix #581: Overzealous Mark Occurrences for single characters
  RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/DefaultOccurrenceMarker.java
  RSyntaxTextArea/src/test/java/org/fife/ui/rsyntaxtextarea/DefaultOccurrenceMarkerTest.java
Labels: bug

#586 Fix #585 FileTypeUtil should identify Rust files
  RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/FileTypeUtil.java
  RSyntaxTextArea/src/test/java/org/fife/ui/rsyntaxtextarea/FileTypeUtilTest.java
Labels: bug

#587 Build with Java 17
  .github/workflows/codeql-analysis.yml
  .github/workflows/gradle.yml
  README.md
  build.gradle
Labels: ci/cd, dependencies
